replicaSetName: rs0
replicaSetHostnames: true

replicaCount: 3
arbiter:
  enabled: true

auth:
  enabled: false

image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 7.0.12-debian-12-r6
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  size: 50Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

arbiter:
  persistence:
    enabled: false

# Node Selector to ensure that the MongoDB pods are placed on specific nodes with the key "data-private"
nodeSelector:
  data-private: "true"

# Pod Affinity and Anti-Affinity
affinity:
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: "app"
              operator: In
              values:
                - mongodb
        topologyKey: "kubernetes.io/hostname"
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "app"
                operator: In
                values:
                  - mongodb
          topologyKey: "kubernetes.io/hostname"

tolerations:
  - key: "data-private"
    operator: "Exists"
    effect: "NoSchedule"